create table
  public.tournament (
    id bigint generated by default as identity not null,
    created date not null,
    name text not null,
    type bigint not null,
    "numberOfRounds" bigint null,
    constraint tournament_pkey primary key (id)
  ) tablespace pg_default;

create table
  public."playerHistory" (
    id bigint generated by default as identity not null,
    "idTournament" bigint not null,
    "idPlayer" bigint not null,
    "playerName" text not null,
    "skillLevel" bigint not null,
    "movementSpeed" bigint null,
    "reactionTime" bigint null,
    strength bigint null,
    "positionRound" bigint not null,
    winner boolean not null,
    constraint playerHistory_pkey primary key (id),
    constraint playerHistory_idTournament_fkey foreign key ("idTournament") references tournament (id)
  ) tablespace pg_default;

create table
  public.players (
    id bigint generated by default as identity not null,
    name text not null,
    "playerTypeId" bigint not null,
    constraint players_pkey primary key (id)
  ) tablespace pg_default;